spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/querydsl
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    sql: debug
